# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86fe6568fe51be9345323ffc54d478354189ae663c2b3ff0f9285fa308a7c8e0dc404f534dedc722c8a07fc4a69fffc48f99bb1f84b8eb8268482343e0ec6ed0

test:
  secret_key_base: 94c3cbfa34f66f4cd46072d4c7648699cb5496a0334fda3b66c13676f0d0aa0ed43bf9f2e9485902299be60433927f74bfb2dd4fef9a90c4782bd1287d4624ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
